version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal  # apunta a tu PostgreSQL local
      - DB_USER=postgres
      - DB_PASS=dayana
      - DB_NAME=PokemonApi
      - DB_PORT=5432
    networks:
      - app-network

networks:
  app-network:
